name: mobile_up
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  provider: ^6.0.0
  shared_preferences: ^2.0.7
  vkio: ^1.3.3
  flutter_login_vk: ^1.0.1
  flutter_cache_manager: ^3.1.2
  cached_network_image: ^3.1.0
  photo_view: ^0.12.0
  open_file: ^3.2.1
  path_provider: ^2.0.4
  intl: ^0.17.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

dependency_overrides:
  async: 2.6.1
  http: 0.12.0+2

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
